trigger:
  branches:
    
pool:
  vmImage: ubuntu-latest
variables: 
  - group: GH
jobs:
  - job: Persons
    steps:
      - template: ./templates/include-person-steps.yml
        parameters:
              PERSONS: 
                - name: "TJ"
                  value: 35
                - name: "TJ2"
                  value: 36
  - job: Terraform
    steps:
      - template: ./templates/include-tf-steps.yml
        parameters:
              FOLDERS: 
                - name: "DEV"
                  value: dev
                - name: "UAT"
                  value: uat
            
