trigger:
  branches:
    include:
      - "main"

pr:
  branches:
    include:
      - "main"
parameters:
  - name: apps
    type: object
    default: 
      - name: 'app1'
        environments:
          - name: 'dev'
            folder: "./dev"
          - name: 'uat'
            folder: "./uat"
pool:
  vmImage: ubuntu-latest
variables: 
  - group: GH
stages:
- template: ./templates/include-tf-stage.yml
  parameters:
    apps: ${{ parameters.apps }}

            
