trigger:
  branches:
    include:
      - "main"

pr:
  branches:
    include:
      - "main"
parameters:
  - name: apps
    type: object
    default: 
      - name: 'app1'
        environments:
          - name: 'dev'
            folder: "./dev"
          - name: 'uat'
            folder: "./uat"


resources:
- template: ./templates/resource.tmpl.yml

pool:
  vmImage: ubuntu-latest
variables: 
  - group: GH
stages:
- template: ./templates/include-tf-stage.yml
  parameters:
    apps: ${{ parameters.apps }}
# jobs:
#   # - job: Persons
#   #   steps:
#   #     - template: ./templates/include-person-steps.yml
#   #       parameters:
#   #             PERSONS: 
#   #               - name: "TJ"
#   #                 value: 35
#   #               - name: "TJ2"
#   #                 value: 36
#   - job: Terraform
#     steps:
#       - template: ./templates/include-tf-stage.yml
#         parameters:
#               FOLDERS: 
#                 - name: "DEV"
#                   value: dev
#                 - name: "UAT"
#                   value: uat
            
