trigger:
  - none
pool:
  vmImage: ubuntu-latest
jobs:
  - job: Persons
    steps:
      - template: ./templates/include-person-steps.yml
        parameters:
              PERSONS: 
                - name: "TJ"
                  age: 35
                - name: "TJ2"
                  age: 36
          
            
