# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest
jobs:
- job: A
  steps:
  - task: Bash@3
    inputs:
      script: | 
        echo 'hello'
- job: B
  steps:
  - task: Bash@3
    inputs:
      script: | 
        echo 'hello B'
