parameters:
  - name : APPS 
    type: object

stages:
- ${{ each app in parameters.APPS }}:
  - stage: ${{ app.name }}
    dependsOn: []
    jobs:
    - ${{ each env in app.environments }}:
      - template: ./include-tf-job.yml   
        parameters:
          APP_NAME: ${{ app.name }}  
          APP_ENV: ${{ env.name }}  
          APP_FOLDER: ${{ env.folder }} 
    - job: output
        steps:
        - task: Bash@3
          displayName: "Output"
          inputs:
            targetType: inline
            script: |
              echo "My output is: $(TFSHOW)"

            
