parameters:
  - name : APPS 
    type: object

stages:
- ${{ each app in parameters.APPS }}:
  - stage: ${{ app.name }}
    dependsOn: []
    jobs:
    - job: Hello
      dependsOn: []
      steps:
      - bash: echo "Hello Ubuntu"

    - job: Hello2
      dependsOn: []
      steps:
      - bash: echo "Hello Windows"
  # - ${{ each env in app.environments }}:
  #   - template: ./include-tf-job.yml   
  #     parameters:
  #       APP_NAME: ${{ app.name }}  
  #       APP_ENV: ${{ env.name }}  
  #       APP_FOLDER: ${{ env.folder }} 
        
