parameters:
  - name : APPS 
    type: object

stages:
- ${{ each app in parameters.APPS }}:
  - stage: ${{ app.name }}
    dependsOn: []
    jobs:
      - ${{ each env in app.environments }}:
        - template: ./include-tf-job.yml   
          parameters:
            APP_NAME: ${{ app.name }}  
            APP_ENV: ${{ env.name }}  
            APP_FOLDER: ${{ env.folder }}
      - job: output
        dependsOn: "APP1_DEV"
        variables:
          FLAG: $[ dependencies.APP1_DEV.outputs['tfplan.FLAG'] ]
          - name: myVarFromJobA
          ${{ if eq(dependencies.APP1_DEV.outputs['tfplan.FLAG'], true) }}:
            value: $[ dependencies.APP1_DEV.outputs['tfplan.TFSHOW'] ]
          ${{ else }}:
            value: "===Nothing to print==="
        steps:
        - task: Bash@3
          displayName: "Output"
          inputs:
            targetType: inline
            script: |
              echo "My output is: $(myVarFromJobA) stage is: $(System.StageName)"

            
