on:
  workflow_dispatch:

env:
  SOME_VAR: "foo"
  ANOTHER_VAR: "bar"

jobs:
  call_reusable:
    permissions:
      contents: read
    strategy:
      matrix:
        env: ["dev"]
    uses: tj-0-tj/tf-rnd-azure-modules/.github/workflows/reusable.yaml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit