on:
  workflow_dispatch:

jobs:
  set_env_vars:
    permissions:
      contents: read
    strategy:
      matrix:
        env: ["dev"]
    outputs:
      SECRET_MAP: ${{ secrets.TEST }}
    steps:
      - run: printenv

  # call_reusable:
  #   permissions:
  #     contents: read
  #   strategy:
  #     matrix:
  #       env: ["dev"]
  #   uses: tj-0-tj/tf-rnd-azure-modules/.github/workflows/reusable.yaml@main
  #   with:
  #     config-path: .github/labeler.yml
  #   secrets: inherit