on:
  workflow_dispatch:

jobs:
  set_env_vars:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    strategy:
      matrix:
        env: ["dev"]
    outputs:
      SECRET_MAP: "testing"
      env_var: ${{vars.TEST_ENV}}
    steps:
      - run: echo ${{secrets.TEST }} | sed 's/./& /g'

  check_envs:
    runs-on: ubuntu-latest
    needs: set_env_vars
    permissions:
      contents: read
      actions: read
    strategy:
      matrix:
        env: ["dev"]
    steps:
      - run: echo "This is : ${{ needs.set_env_vars.outputs.SECRET_MAP }}"

  call_reusable:
    needs: set_env_vars
    permissions:
      contents: read
      actions: read
    strategy:
      matrix:
        env: ["dev"]
    uses: tj-0-tj/tf-rnd-azure-modules/.github/workflows/reusable.yaml@main
    with:
      config-path: ${{ needs.set_env_vars.outputs.SECRET_MAP }}
    secrets: inherit