jobs:
  call_reusable:
    runs-on: ubuntu-latest
    env:
      SOME_VAR: "foo"
      ANOTHER_VAR: "bar"
    steps:
      - name: call reusable
        uses: ./.github/workflows/reusable.yml
        with:
          env_vars: ${{ toJson(env) }}
