on:
  workflow_dispatch:

env:
  SOME_VAR: "foo"
  ANOTHER_VAR: "bar"

jobs:
  call_reusable:
    strategy:
      matrix:
        env: ["dev"]
    uses: tj-0-tj/tf-rnd-azure-modules/.github/workflows/reusable.yaml@main
    with:
      env_vars: ${{ toJson(env) }}
