on:
  workflow_dispatch:

jobs:
  set_env_vars:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        env: ["dev"]
    outputs:
      SECRET_MAP: "testing"
    steps:
      - run: echo "${{ secrets.TEST }}"

  check_envs:
    runs-on: ubuntu-latest
    needs: set_env_vars
    permissions:
      contents: read
    strategy:
      matrix:
        env: ["dev"]
    steps:
      - run: echo ${{ needs.set_env_vars.outputs.SECRET_MAP }}

  call_reusable:
    permissions:
      contents: read
    strategy:
      matrix:
        env: ["dev"]
    uses: tj-0-tj/tf-rnd-azure-modules/.github/workflows/reusable.yaml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit