on:
  workflow_dispatch:

env:
  SOME_VAR: "foo"
  ANOTHER_VAR: "bar"

jobs:
  call_reusable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ["dev"]
    steps:
      - name: Checkout Code
        uses: tj-0-tj/tf-rnd-azure-modules/.github/workflows/reusable.yaml@main
        with:
          env_vars: ${{ secrets.TEST }}
