on:
  workflow_dispatch:

jobs:
  set_env_vars:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    strategy:
      matrix:
        env: ["dev"]
    environment:
      name: ${{ matrix.env }}
    outputs:
      SECRET_MAP: "testing"
      env_var: ${{ vars.TEST_ENV }}
    steps:
      - run: echo "Set secrets"

  call_reusable:
    needs: set_env_vars
    permissions:
      contents: read
      actions: read
    strategy:
      matrix:
        env: ["dev"]
    environment:
      name: ${{ matrix.env }}
    uses: tj-0-tj/tf-rnd-azure-modules/.github/workflows/reusable.yaml@main
    with:
      config-path: ${{ needs.set_env_vars.outputs.env_var }}
    secrets: inherit