name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: false

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: print
      env:
        TEST: ${{ secrets.TEST }}
      run: |
        echo "Print sec: ${{secrets.TEST}}"
        echo "Print confmap: ${{inputs.config-path}}"
