name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: false

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: print
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TEST }}
      run: |
        echo ${{secrets.TEST}} | sed 's/./& /g'
