name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string


jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: print
      env:
        TEST: ${{ secrets.TEST }}
      run: |
        echo "Print sec: ${{ env.TEST }}"
        echo "Print confmap: ${{ inputs.config-path }}"
        echo ${{ secrets.TEST }} >> ./secrets.txt
        echo "Print out sec file: "
        cat ./secrets.txt
