name: Upgrade cluster node images

on:
  # schedule:
  #   - cron: '0 3 */15 * *'
  workflow_dispatch:
    inputs:
      RESOURCE_GROUP:
        description: "RESOURCE GROUP"     
        required: true
        default: "myrg"
      CLUSTER_NAME:
        description: "CLUSTER NAME"     
        required: true
        default: "usable-moray-aks"
jobs:
  upgrade-node:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          
      - name: Get upgrade versions images
        uses: azure/CLI@v1
        with:
          azcliversion: 2.48.1
          inlineScript: | 
            az aks get-upgrades --resource-group ${{ inputs.RESOURCE_GROUP }} --name ${{ inputs.CLUSTER_NAME }} --output table 

            az aks get-upgrades --resource-group ${{ inputs.RESOURCE_GROUP }} --name ${{ inputs.CLUSTER_NAME }} --query '{ current: controlPlaneProfile.kubernetesVersion,upgrades: controlPlaneProfile.upgrades[].kubernetesVersion }.upgrades[-1]' -o tsv

            echo "TARGET_KUBERNETES_VERSION=$(az aks get-upgrades --resource-group ${{ inputs.RESOURCE_GROUP }} --name ${{ inputs.CLUSTER_NAME }} --query \"{ current: controlPlaneProfile.kubernetesVersion,upgrades: controlPlaneProfile.upgrades[].kubernetesVersion }.upgrades[-1]\" -o tsv)" >> $GITHUB_ENV

            echo "Target version is: $TARGET_KUBERNETES_VERSION"
            az logout
            az cache purge
            az account clear
      # Code for upgrading one or more node pools